### ISSUE TITLE
Using native async await

### ISSUE THREAD

**Issue by GProst** [relay-tools/react-relay-network-modern-ssr#6]
I tried to import `react-relay-network-modern-ssr/node8/server` to use 'react-relay-network-modern/node8' but it looks like `react-relay-network-modern-ssr/node8/server` references to `react-relay-network-modern/lib` and not `node8`... Is it a mistake or I don't undertand something?

**Comment by nodkz** [comment]
Thanks for pointing to this error. Will be fixed in next version.
