### ISSUE TITLE
Please improve the documentation

### ISSUE THREAD

**Issue by mxrguspxrt** [relay-tools/react-relay-network-modern-ssr#8]
Hello!

Thank you for your effort and awesome libary!

Could you please be so kind and provide working example in your README. (Instead of referring 3rd party full examples.)

Apollo has SSR in their main documentation, getting Relay to work with SSR is not so simple experience (Relay Modern > Relay network modern > Relay network modern SSR > Artsy examples for working project).

https://www.google.com/search?q=prepareGraphQLContext

**Comment by nodkz** [comment]
A little bit was improved an example. Now it should be easier to follow.

**Comment by mxrguspxrt** [comment]
Thank you! This helped me a lot.

May the force be with you! :)
